JohnXLivingston/peertube-plugin-livechat

- documentation/tutorials/prosody.md
Despite the common confusion, there's no prosody version 11, the latest
version at the time of this writing is 0.11.8
> Correct Prosody verison numbers

- languages/settings/de.yml
I shortened the translations because there were truncated (https://github.com/JohnXLivingston/peertube-plugin-livechat/pull/156#issuecomment-1432575934).
I also shortened the text for the two option buttons so they should be fixed too. I only counted the visible characters, so it would be great if you could test it.
The description of the automatic color detection had ` on the end of the line. I think it is not necessary there, so I removed it. (Please correct me if this is wrong.)
- Shortened Room Typ button text
- Shortened Room Typ option button text
- Shortened Share url option button text
- Removed `
> German Translation shortened

- support/documentation/content/documentation/admin/advanced/xmpp_clients.en.md
This fixes a small error in the docker certbot documentation, in find -exec.  Without this, the renewal will result in an infinite loop of failure because of the way `\;` is interpreted.
> Fix docker certbot renewal documentation

- CHANGELOG.md
- server/lib/federation/outgoing.ts
- server/lib/federation/types.ts
- server/lib/uri/webchat.ts
- support/documentation/content/contributing/translate/_index.en.md
- support/documentation/content/contributing/translate/_index.fr.md
- support/documentation/content/technical/_index.de.md
- support/documentation/content/technical/_index.en.md
- support/documentation/content/technical/_index.fr.md
- support/documentation/content/technical/_index.ja.md
- support/documentation/content/technical/thirdparty/_index.de.md
- support/documentation/content/technical/thirdparty/_index.en.md
- support/documentation/content/technical/thirdparty/_index.fr.md
- support/documentation/content/technical/thirdparty/_index.ja.md
Implementing the [FEP-1970](https://codeberg.org/John_Livingston/fep/src/branch/fep-1970/fep/1970/fep-1970.md) draft for ActivityPub chat declaration.
See https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/113 for more context.
Chat discovery using ActivityPub will be documented here (as soon as the PR is merged to the `documentation` branch):
https://johnxlivingston.github.io/peertube-plugin-livechat/technical/thirdparty/
Some notes about choices that where made.
After reading a lot of specification, documentation, and other FEPs, i came up with this simple proposal. It seems elegant, and is consistent with other draft FEP (for example [FEP 0ea0](https://codeberg.org/fediverse/fep/src/branch/main/fep/0ea0/fep-0ea0.md)).
The livechat plugin needs more data to know how to …
> 113 tk2211 0110 activypub chat standardization

- .gitignore
- .gitmodules
- CHANGELOG.md
- conversejs/build-conversejs.sh
This changes the way converse is integrated:
- removal of the git submodule
- shallow clone in the conversejs dir (with version number)
- change `converse.js` name to `conversjs` for consistency sake
- update of the converse build/override script
supersedes #221 
-----------
comments:
J'écris en français, ce sera plus rapide :p
Alors, dans les trucs à vérifier:
Regarder dans le dossier conversejs/custom: j'y surcharge quelques templates/fichiers js.
Il peut être utile de faire un diff de ConverseJS, pour voir si des choses ont été renommées dans les fichiers originaux, et si ça peut poser pb.
De même, j'ai un fichier livechat.scss.
Faire un diff des CSS originales, et voir si y'a des changements. Si oui, jeter un oeil, voir si ça peut impacter livechat.scss.
Bon, je me rend compte que ce …
> build converse another way, and upgrade to v10

- CHANGELOG.md
- client/admin-plugin-client-plugin.ts
- languages/en.yml
- prosody-modules/mod_muc_ban_ip/README.markdown
- prosody-modules/mod_muc_ban_ip/mod_muc_ban_ip.lua
- server/lib/prosody/config.ts
- server/lib/prosody/config/content.ts
- server/lib/settings.ts
- support/documentation/content/en/documentation/admin/settings.md
New settings: "Ban anonymous user's IP when user is banned from a chatroom":
* if enabled, every time a streamer bans an anonymous user, it will ban its IP on the chat server,
* banned IPs are logged on disk, so server's admin can use them to feed fail2ban (for example),
* option disabled by default, because could be used to create trapped-rooms on public servers
New settings: "Ban anonymous user's IP when user is banned from a chatroom":
* if enabled, every time a streamer bans an anonymous user, it will ban its IP on the chat server,
* banned IPs are logged on disk, so server's admin can use them to feed fail2ban (for example),
* option disabled by default, because could be used to create trapped-rooms on public servers
https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/2 …
> Auto ban anonymous IP:

- CHANGELOG.md
- package-lock.json
- package.json
- server/lib/debug.ts
- server/lib/prosody/certificates.ts
* On some Ubuntu server, the self-signed certificates generation fails:
* See [issue #268](https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/268)
* This prevents the bot to connect to the server
* As a fallback, we directly call openssl to generate the certificates
> Fix self-signed certificates on ubuntu + v8.0.2:

- CHANGELOG.md
- conversejs/lib/converse-params.ts
Setting `prune_messages_above` to 100 is confirmed to fix this issue.
I made some tests with my new stress-test tools. See the results here:
https://github.com/JohnXLivingston/livechat-perf-test/tree/main/tests/10-browser-vs-flooding-bot
(runs `2023-12-18`, `2023-12-19`, `03-prune-message-above-100`, `04-prune-message-above-100-converse-patched`)
TL;DR:
Before:
After:
https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/140
> Fix #140: using ConverseJS `prune_messages_above` to purge old messages

- CHANGELOG.md
- conversejs/custom/shared/styles/livechat.scss
- conversejs/custom/templates/muc-bottom-panel.js
Adding a label on the nickname prompt.
#287
> Fix #287: add a label before the anonymous nickname prompt.

- CHANGELOG.md
- conversejs/builtin.ts
- conversejs/lib/converse-params.ts
Hide nickname changes when previous nickname was like "Anonymous 12345". Helps to improve performances when massive anonymous users are joining (#138), and prevent displaying unnecessary messages (#111).
> UI/UX improvment:

- CHANGELOG.md
- conversejs/build-conversejs.sh
- conversejs/builtin.ts
With this commit, anonymous users are displayed at the end of the room participants.
* #136 
* #111
> Fix #136: display anonymous users at the end of the participants list

- CHANGELOG.md
- server/lib/prosody/config/content.ts
Anonymous users can't use carbons, as they cannot connect with multiple tabs on the same anonymous account.
So we disable carbons on the anonymous virtualhost, to improve performances.
See here for some performances tests: https://github.com/JohnXLivingston/livechat-perf-test/tree/main/tests/50-anonymous-carbons
> Fix #295: Prosody: disabling message carbons for anonymous users.

- CHANGELOG.md
- prosody-modules/mod_vcard_peertubelivechat/mod_vcard_peertubelivechat.lua
* Peertube users avatars optimization (Fix #303):
* avoid multiple parallel request to load same avatar from Peertube
* send "item-not-found" stanza when no avatar, instead of a vCard without avatar
https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/303
> 303 registered users avatars avoid multiple parallel request to peertube

- CHANGELOG.md
- server/lib/prosody/config/affiliations.ts
* This was related to the fact that the bot was owner because of the "admins" Prosody config key, and not registered in the room.
* To fix it, i added the bot as owner when creating rooms.
* This means that the fix only work for newly created rooms.
* There might still be an issue in ConverseJS or Prosody, don't know exactly where. (XEP-0045 as no "muc admin" concept)
#322
> Fix #322: "Sepia is no longer an owner of this groupchat" message when joining the chat

- CHANGELOG.md
- conversejs/build-conversejs.sh
- conversejs/lib/converse-params.ts
Implementing [XEP-0392](https://xmpp.org/extensions/xep-0392.html) to have random colors on users nicknames.
Implementation in ConverseJS upstream available here:
https://github.com/conversejs/converse.js/pull/3347
Here is the commit on the livechat specific ConverseJS:
https://github.com/JohnXLivingston/converse.js/commit/ae1b576d5c9d2691df896d603cd65726b3e04480
https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/143
> Implement #143: User colors

- CHANGELOG.md
- client/admin-plugin-client-plugin.ts
- languages/en.yml
- server/lib/prosody/config.ts
- server/lib/prosody/config/content.ts
- server/lib/settings.ts
- support/documentation/content/en/documentation/admin/settings.md
New setting to listen C2S connection on non-localhost interfaces (#377).
#377
> New setting to listen C2S connection on non-localhost interfaces (#377).

- CHANGELOG.md
- server/lib/prosody/ctl.ts
Feel free to close & address in a different manner if you have a preferred solution. I'm not super deep into JS/TS stuff, just upstreaming our downstream workaround.
---
Add callbacks to deregister the interval callback when stdin closes or errors out.
De-escalates the issue to the following messages:
- Usually:
```
[...]
server # [   69.269893] peertube[1411]: [localhost:9000 peertube-plugin-livechat] 2024-06-11 20:48:10.893 debug: ProsodyCtl was called in yesMode, writing to standard input.
server # [   69.281086] peertube[1411]: [localhost:9000 peertube-plugin-livechat] 2024-06-11 20:48:10.902 debug: ProsodyCtl was called in yesMode, writing to standard input.
server # [   69.291426] peertube[1411]: [localhost:9000 peertube-plugin-livechat] 2024-06-11 20:48:10.914 debug: ProsodyCtl was …
```
> Deregister prosodyctl interval callback when spawn.stdin disappears

- CHANGELOG.md
- server/lib/custom-fields.ts
So that the Android Peertube Live app can enable the chat in one request.
See #400 for more information.
This concern the plugin when the settings "chat-per-live-video" is true (which is default). In other words, when streamers can enable/disable chat for each lives by themselves.
Before this, when a live was created, the chat was not enabled before the users edits chat meta data, and submit the form.
This PR allow to pass the `livechat-active` parameter.
#400
> Handle livechat-active parameter on live creation endpoint.

- CHANGELOG.md
- assets/styles/video/_container.scss
On small devices, chat is not high enough.
#433
> Fix: increase chat height on small screens, try to better detect the device viewport size and orientation.

- CHANGELOG.md
- conversejs/build-conversejs.sh
Fix various issues about custom emojis vs upper/lower case.
#618
> Fix #618: Fix custom emojis vs upper/lower case.

- CHANGELOG.md
- server/lib/routers/emojis.ts
> Fix #660: don't send headers twice on emoji router errors.

- CHANGELOG.md
- conversejs/custom/shared/components/draggables/index.js
- conversejs/custom/shared/components/draggables/styles/draggables.scss
- conversejs/custom/shared/styles/_peertubetheme.scss
- conversejs/custom/shared/styles/livechat.scss
- conversejs/custom/templates/muc-bottom-panel.js
- conversejs/lib/plugins/livechat-specific/toolbar.ts
- conversejs/loc.keys.js
- languages/en.yml
- languages/fr.yml
- auto focus message field after anonymous user has entered nickname.
- add draggable items touch screen handling
- when clicking on the occupant list panel button, hides offline users
- add button to go to the end of the chat when chat scrolled
- set custom emojis max height to text height + bigger when posted alone
* Fix #329
* Fix #392
* Fix #506
* Fix #547
* Fix #503
Custom emojis no longer break the text height. If posted alone, it is displayed a bit bigger like regular emoji.
Button to go to the last message if chat is scrolled
But does not show up if there's new messages for which there's already a button
> Various UX/UI Improvments

- CHANGELOG.md
- client/tsconfig.json.license
- languages/en.yml
- languages/es.yml
- languages/fr.yml
- package-lock.json
- package-lock.json.license
- package.json
- package.json.license
- server/tsconfig.json
- shared/lib/config.ts
Makes it possible to activate chat on short uuid videos.
Fixes [#75](https://github.com/JohnXLivingston/peertube-plugin-livechat/issues/75)
> Short uuid handling

- CHANGELOG.md
- client/common/configuration/services/channel-details.ts
There was a regression some months ago in the "bot timer" functionnality. In the channels settings, the delay between two quotes is supposed to be in minutes, but in fact we applied seconds. We don't have any way to detect if the user meant seconds or minutes when they configured their channels (it depends if it was before or after the regression). So we encourage all streamers to go through their channel settings, check the frequency of their bot timers (if enabled), set them to the correct value, and save the form. Users must save the form to be sure to apply the correct value.
#626
> Fix #626: Bot timer was buggy, using seconds as delay instead of minutes
